### ISSUE TITLE
copa patches for linux?

### ISSUE THREAD

**Issue by dtaht** [venkatarun95/ccp_copa#3]
I liked the copa paper, particularly how gently copa tried to adjust it's rate seemed ideal for a fq_codeled environment. Got linux patches for it?

**Comment by venkatarun95** [comment]
Thanks for the interest! In steady-state congestion-avoidance mode, Copa doesn't react to loss/ecn. But, you are right, many ideas in Copa can be readily adopted for that environment. We could have a scheme for the wide internet that reacts gently to ECN like DCTCP.

We are developing a kernel module for Copa and plan to push it upstream.

Meanwhile this repository can be used with [CCP](https://ccp-project.github.io/), which is a kernel module that interfaces with the user-space program in this repository to provide a traditional Linux congestion control variant.

**Comment by dtaht** [comment]
Please stay in touch. I regularly evaluate various tcp's in my lab, most recently against the new sch_cake but also against things like wifi (see some new kernel stuff fot netem "slotting".

as to the closest coherent thing I've written lately about ecn, see: https://github.com/systemd/systemd/issues/9748

**Comment by venkatarun95** [comment]
Will do! Thanks! We are very interested in testing Copa on various test-beds. I will update you when we have a kernel module.

**Comment by limlynn** [comment]
Hello, have you worked on a kernel module of copa? I really appreciate any help you can provide.

**Comment by venkatarun95** [comment]
Hello, we do not have a kernel module for Copa. This repo provides a CCP implementation. It works just like a kernel module in the sense that regular kernel sockets can use Copa. 

CCP provides a single kernel module for multiple CCAs. There are user-space programs that implements various CCAs (e.g. this repo implements Copa) and talk to the kernel module to set the correct congestion window etc.
